"""Local submission preflight: distinguish implemented checks from GPU evidence."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

from .contract import FAMILIES
from .data import COUNTS, module, observable_id, read_records, replay_reference
from .runtime import digest


def verify(base, *, recertify=False):
    base = Path(base)
    checks, blockers = {}, []
    seen = set()
    stats = {}
    for split, n in COUNTS.items():
        path = base / "data" / ("private" if split == "hidden" else "public") / (split+".jsonl")
        if not path.exists():
            blockers.append("missing_"+split)
            continue
        rows = read_records(path)
        quotas = {f: {tier: sum(r["family"] == f and r["tier"] == tier for r in rows)
            for tier in ("hard", "harder")} for f in FAMILIES}
        complete = len(rows) == 16*n and all(v == n//2 for q in quotas.values() for v in q.values())
        if not complete:
            blockers.append("incomplete_"+split)
        if len({r["id"] for r in rows}) != len(rows):
            blockers.append("duplicate_ids_"+split)
        for record in rows:
            identity = observable_id(record)
            if identity in seen:
                blockers.append("duplicate_observable_instance")
            seen.add(identity)
            if recertify:
                module(record["family"]).certify(record)
                replay_reference(record)
        stats[split] = {"count": len(rows), "complete": complete,
            "sha256": digest(rows), "recertified_now": recertify}
    checks["data"] = stats
    vendor = base / "assets/vendor/miniwob"
    manifest = json.loads((vendor/"SOURCE_MANIFEST.json").read_text())
    for name, row in manifest["files"].items():
        content = (vendor/name).read_bytes()
        if len(content) != row["bytes"] or hashlib.sha256(content).hexdigest() != row["sha256"]:
            blockers.append("upstream_asset_hash_mismatch")
    checks["native_assets"] = {"files":len(manifest["files"]), "revision":manifest["revision"]}
    lock = json.loads((base/"configs/model_lock.json").read_text())
    checks["model_source"] = {"repo":lock["repo"],"revision":lock["revision"],"active_mode":"System 2",
        "license":lock["license"],"manifest_files":len(lock["files"])}
    gpu_evidence = base / "evidence/gpu"
    # These must be real outputs generated by the fixed commands, never fake scores.
    for name in ("gpu-smoke.json", "b0_judge.json", "b1_judge.json", "research_trajectory.json"):
        evidence_path = gpu_evidence / name
        if not evidence_path.is_file():
            blockers.append("missing_real_gpu_evidence:"+name)
            continue
        try:
            evidence = json.loads(evidence_path.read_text())
            expected_status = "inference_completed" if name == "gpu-smoke.json" else "complete"
            if evidence.get("status") != expected_status:
                raise ValueError("Incomplete evidence")
            if name in ("b0_judge.json", "b1_judge.json"):
                if evidence.get("completed") != 96 or set(evidence.get("by_type", {})) != set(FAMILIES):
                    raise ValueError("Incomplete Judge result")
            if name != "research_trajectory.json" and evidence.get("model", {}).get("revision") != lock["revision"]:
                raise ValueError("Wrong or absent model revision")
        except (ValueError, TypeError, AttributeError):
            blockers.append("invalid_or_incomplete_gpu_evidence:"+name)
    if not (base/"evidence/official_validation.json").is_file():
        blockers.append("official_harbor_validation_and_trajectory_upload_not_run")
    if not (base/"evidence/linux_environment_validation.json").is_file():
        blockers.append("target_docker_linux_chromium_not_validated")
    calibration_path = gpu_evidence / "calibration.json"
    if not calibration_path.is_file():
        blockers.append("game_model_difficulty_calibration_not_measured")
    else:
        calibration = json.loads(calibration_path.read_text())
        if calibration.get("status") != "complete" or calibration.get("completed") != 128:
            blockers.append("incomplete_real_model_difficulty_calibration")
        if calibration.get("difficulty_calibration", {}).get("requires_author_review", True):
            blockers.append("difficulty_calibration_requires_review")
    return {"schema_version":1, "checks":checks, "ready_for_submission":not blockers,
        "blockers":sorted(set(blockers)), "no_model_results_inferred_from_reference_success":True}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", default=".")
    parser.add_argument("--recertify", action="store_true")
    parser.add_argument("--output", default="evidence/readiness.json")
    args = parser.parse_args()
    result = verify(args.base, recertify=args.recertify)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(result, indent=2)+"\n")
    print(json.dumps({"ready_for_submission":result["ready_for_submission"],"blockers":result["blockers"]}))


if __name__ == "__main__":
    main()
